### PR TITLE
BUG: supports_sane_rowcount = False

### LINKED ISSUE #3: UPDATES fail intermittently
Error message:
```
sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'mytable' expected to update 1 row(s); 0 were matched.
```
When I pip uninstalll `sqlalchemy-sybase` it works fine for some reason.

Version info:
sqlalchemy - 1.3.17
sqlalchemy-sybase - 1.0.3

More information to be added later as I have it.

### PR DESCRIPTION
**Pull request by snowman2**
Closes #3 

This setting change seems to fix the issue.

### CODE REVIEW

**Comment by gordthompson** [comment]
Thanks, Alan. I flipped that bit to `True` back in May because a lot of the "sane_rowcount" stuff seemed to be related to issues with much older versions of pyodbc, and my initial testing with current pyodbc and SAP ASE ODBC seemed fine with it. Sorry for the inconvenience.

**Comment by snowman2** [comment]
That makes sense - no worries. Most things seemed to work, just this random hiccup. The `pyodbc` version I used for testing was the current latest `4.0.30`. I wonder if it has to do with the database `Adaptive Server Enterprise/16.0 SP02` I am using?

**Comment by gordthompson** [comment]
> 
> 
> I wonder if it has to do with the database `Adaptive Server Enterprise/16.0 SP02` I am using?

Seems unlikely to me. These rowcount issues have been around for a long time and they strike me as the sort of thing that is so baked into the backend (or the ODBC driver, or both) that they probably won't get fixed on their own, but if they do happen to get fixed as a side-effect of some other change most people won't notice because they're already using some sort of workaround anyway.

**Comment by snowman2** [comment]
Interesting :thinking:. Thanks for the quick release :+1:

**Pull request merged**
