### PR TITLE
ENH: Return ID of inserted row

### PR DESCRIPTION
**Pull request by snowman2**
Related to: https://github.com/sqlalchemy/sqlalchemy/issues/5311

### CODE REVIEW

**Comment by gordthompson** [comment]
This is great. Thanks, Alan!

**Comment by snowman2** [comment]
Thanks @gordthompson :+1:. Is there another release planned in the near future?

**Comment by gordthompson** [comment]
Done. (1.0.3)

**Comment by snowman2** [comment]
Thanks 👍

**Pull request merged**
